### ISSUE TITLE
Composer validation broken

### ISSUE THREAD

**Issue by danepowell** [grasmash/drupal-module-evaluator#19]
It seems that no matter what module is being scanned (e.g. Acquia Connector), the Evaluator reports composer.json to be invalid.

The proximal cause seems to be that it runs `composer validate` in the current working directory, which is going to be the drupal-module-evaluator directory if you are following the instructions in the readme: https://github.com/grasmash/drupal-module-evaluator/blob/master/src/EvaluateCommand.php#L703

However, even if you give a `$download_path` to that function it still won't work because the fixture composer.json is explicitly removed during setup: https://github.com/grasmash/drupal-module-evaluator/blob/master/src/EvaluateCommand.php#L545

I'm not sure why composer.json is removed. @grasmash If you let me know how you want to resolve this I can open a PR.

**Comment by grasmash** [comment]
I'm not sure why the composer.json is removed. Presumably it caused a problem. Let's add it back and see what happens.
