### ISSUE TITLE
Deprecation errors are not just deprecation errors

### ISSUE THREAD

**Issue by goba** [grasmash/drupal-module-evaluator#6]
See this line:

https://github.com/grasmash/drupal-module-evaluator/blob/06cbfce0752505efa06785853672c52f0d9c9133/src/EvaluateCommand.php#L490

What the code does is it runs all of phpstan's checks on it. It does not use the Drupal autoloader supported integrations, etc. so if you look at your actual results, you would mostly get a bunch of "autoloading failed" alongside a lot of misc PHP coding style issues and not much deprecation errors. This results in totally wrong numbers.

https://glamanate.com/blog/testing-your-drupal-code-base-deprecated-code-usage-phpstan explains that you need a custom .neon file to configure phpstan, etc. It has dependencies with other neon files in composer dependencies to make the autoloading, etc. work. See https://git.drupalcode.org/project/upgrade_status/blob/8.x-1.x/deprecation_testing.neon where we merged those together because we cannot be sure where the composer dependencies or the module will end up. You can work from either to make your results actually counting deprecations.

**Comment by grasmash** [comment]
I believe this has been resolved by replacing phpstan with drupal-check.
